### GET all patients
GET http://localhost:3000/patients

### GET patient by id
GET  http://localhost:3000/patients/b12a40dc-8b27-11ee-ba20-1295b4c7c998

### POST patient
POST  http://localhost:3000/patients
Content-Type: application/json

{
    "firstName": "Lucas Octavio",
    "familyName": "Fernandez Marquez",
    "phoneNumber": "+34600000001",
    "address": "lofernandez@gmail.com",
    "details": "Historial"
}

### PATCH (update) Patient
PATCH http://localhost:3000/patients/b12a40dc-8b27-11ee-ba20-1295b4c7c998
Content-Type: application/json

{
    "phoneNumber": "+34600000005"
}